#######################################
#####  OfflineTeleporter Config   #####
#######################################
dontTouch:
  # This gets replaced during compile with the version in the pom.
  version: %VERSION%