name: Offline Teleporter
main: com.gmail.sevrius.OfflineTeleporter.OfflineTeleporter
version: 0.1

commands:
   otp:
      description: Teleports you to an offline player.
      usage: /<command> [player]
   cookie:
      description: Gives a player a Cookie!
      usage: /<command> [player]
   otphere:
      description: Allows you to set the player's "spawn" position
      usage: /<command> [player] {message}
      
permissions:
    otp.otp:
        description: Let's you teleport to a players logout location!
        default: false
    otp.cookie:
        description: Let's you give players cookies!
        default: false
    otp.otphere:
        description: Allows you to set the player's "spawn" position
        default: false